game:GetService("TextChatService").TextChannels.RBXGeneral:SendAsync("-ch")
task.wait(2)
game:GetService("TextChatService").TextChannels.RBXGeneral:SendAsync("-gh 139904067056008 72292903231768 84451219120140 95290698984301 108186273151388 13058395763")
-- Genesis Rigs ^
--game:GetService("TextChatService").TextChannels.RBXGeneral:SendAsync("-gh 13421786478 17374851733 17374846953 14255562939 14255560646")
-- Krypton Rigs ^
task.wait(3.5)
-- Neptunian V v
--game:GetService("TextChatService").TextChannels.RBXGeneral:SendAsync("-gh 5316479641")
-- Star Glitcher v
--game:GetService("TextChatService").TextChannels.RBXGeneral:SendAsync("-gh 4458601937 4506945409 4794315940 4315489767")
-- Sniper v
game:GetService("TextChatService").TextChannels.RBXGeneral:SendAsync("-gh 5168118559")


--Bullet
task.wait(3)
game:GetService("TextChatService").TextChannels.RBXGeneral:SendAsync("-gh 4504231783")

--Perm Death after loading hats
task.wait(3.5)
game:GetService("TextChatService").TextChannels.RBXGeneral:SendAsync("-pd")