if not isfolder("Dances") then
	makefolder("Dances")
end
local HowMuch = 25
task.spawn(function()
	warn("Downloading.")
	task.wait(0.2)
	warn("Downloading..")
	task.wait(0.2)
	warn("Downloading...")
end)

if not isfile("Dances/A Hat in Time OST (Seal the Deal) Peace and Tranquility.mp3") then
	writefile("Dances/A Hat in Time OST (Seal the Deal) Peace and Tranquility.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/A%20Hat%20in%20Time%20OST%20%5BSeal%20the%20Deal%5D%20-%20Peace%20and%20Tranquility.mp3?raw=true"))
	warn("A Hat in Time OST (Seal the Deal) Peace and Tranquility Downloaded! 1/"..tostring(HowMuch))
end

if not isfile("Dances/Arcology On Permafrost.mp3") then
	writefile("Dances/Arcology On Permafrost.mp3",
	game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/Arcology%20On%20Permafrost.mp3?raw=true"))
	warn("Arcology On Permafrost Downloaded! 2/"..tostring(HowMuch))
end

if not isfile("Dances/Assumptions.mp3") then
	writefile("Dances/Assumptions.mp3",
	game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/Assumptions.mp3?raw=true"))
	warn("Assumptions Downloaded! 3/"..tostring(HowMuch))
end

if not isfile("Dances/balls.mp3") then
	writefile("Dances/balls.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/balls.mp3?raw=true"))
	warn("Balls Downloaded! 4/"..tostring(HowMuch))
end

if not isfile("Dances/billy.mp3") then
	writefile("Dances/billy.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/billy.mp3?raw=true"))
	warn("Billy Downloaded! 5/"..tostring(HowMuch))
end

if not isfile("Dances/bloodpop.mp3") then
	writefile("Dances/bloodpop.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/bloodpop.mp3?raw=true"))
	warn("Bloodpop Downloaded!6/"..tostring(HowMuch))
end

if not isfile("Dances/Bumblebee.mp3") then
	writefile("Dances/Bumblebee.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/Bumblebee.mp3?raw=true"))
	warn("Bumblebee Downloaded! 7/"..tostring(HowMuch))
end

if not isfile("Dances/caramell.mp3") then
	writefile("Dances/caramell.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/caramell.mp3?raw=true"))
	warn("caramell Downloaded! 8/"..tostring(HowMuch))
end

if not isfile("Dances/chronoshift.mp3") then
	writefile("Dances/chronoshift.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/chronoshift.mp3?raw=true"))
	warn("chronoshift Downloaded! 9/"..tostring(HowMuch))
end

if not isfile("Dances/CLUB PENGUIN DANCE.mp3") then
	writefile("Dances/CLUB PENGUIN DANCE.mp3",
	game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/CLUB%20PENGUIN%20DANCE.mp3?raw=true"))
	warn("CLUB PENGUIN DANCE Downloaded! 10/"..tostring(HowMuch))
end

if not isfile("Dances/dancingin.mp3") then
	writefile("Dances/dancingin.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/dancingin.mp3?raw=true"))
	warn("dancingin Downloaded! 11/"..tostring(HowMuch))
end

if not isfile("Dances/dancingwit.mp3") then
	writefile("Dances/dancingwit.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/dancingwit.mp3?raw=true"))
	warn("dancingwit Downloaded! 12/"..tostring(HowMuch))
end

if not isfile("Dances/DO THE FLOP.mp3") then
	writefile("Dances/DO THE FLOP.mp3",
	game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/DO%20THE%20FLOP.mp3?raw=true"))
	warn("DO THE FLOP Downloaded! 13/"..tostring(HowMuch))
end

if not isfile("Dances/Domino.mp3") then
	writefile("Dances/Domino.mp3",
	game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/Domin.mp3?raw=true"))
	warn("Domino Downloaded! 14/"..tostring(HowMuch))
end

if not isfile("Dances/Doodle.mp3") then
	writefile("Dances/Doodle.mp3",
	game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/Doodle.mp3?raw=true"))
	warn("Doodle Downloaded! 15/"..tostring(HowMuch))
end

if not isfile("Dances/doodle - Zachz Winner.mp3") then
	writefile("Dances/doodle - Zachz Winner.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/doodle%20-%20Zachz%20Winner.mp3?raw=true"))
	warn("doodle - Zachz Winner Downloaded! 16/"..tostring(HowMuch))
end

if not isfile("Dances/Down.mp3") then
	writefile("Dances/Down.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/Down.mp3?raw=true"))
	warn("Down Downloaded! 17/"..tostring(HowMuch))
end

if not isfile("Dances/dr.wav") then
	writefile("Dances/dr.wav",
	game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/dr.wav?raw=true"))
	warn("dr Downloaded! 18/"..tostring(HowMuch))
end

if not isfile("Dances/drip.mp3") then
	writefile("Dances/drip.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/drip.mp3?raw=true"))
	warn("drip Downloaded! 19/"..tostring(HowMuch))
end

if not isfile("Dances/faster.ogg") then
	writefile("Dances/faster.ogg",
	game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/faster.ogg?raw=true"))
	warn("faster Downloaded! 20/"..tostring(HowMuch))
end

if not isfile("Dances/freeflow.mp3") then
	writefile("Dances/freeflow.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/freeflow.mp3?raw=true"))
	warn("freeflow Downloaded! 21/"..tostring(HowMuch))
end

if not isfile("Dances/frightfunk.mp3") then
	writefile("Dances/frightfunk.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/frightfunk.mp3?raw=true"))
	warn("frightfunk Downloaded! 22/"..tostring(HowMuch))
end

if not isfile("Dances/gangnamm.mp3") then
	writefile("Dances/gangnamm.mp3",
	game:HttpGet("https://github.com/Gelatekussy/GelatekHubSongs/blob/main/gangnamm.mp3?raw=true"))
	warn("gangnamm Downloaded! 23/"..tostring(HowMuch))
end

if not isfile("Dances/griddy.mp3") then
	writefile("Dances/griddy.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/griddy.mp3?raw=true"))
	warn("gridd yDownloaded! 24/"..tostring(HowMuch))
end

if not isfile("Dances/heavylove.mp3") then
	writefile("Dances/heavylove.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/heavylove.mp3?raw=true"))
	warn("heavylove Downloaded! 25/"..tostring(HowMuch))
end

if not isfile("Dances/kazot.mp3") then
	writefile("Dances/kazot.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/kazot.mp3?raw=true"))
	warn("kazot Downloaded! 26/"..tostring(HowMuch))
end

if not isfile("Dances/leftrigth.mp3") then
	writefile("Dances/leftrigth.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/leftrigth.mp3?raw=true"))
	warn("leftrigth Downloaded! 27/"..tostring(HowMuch))
end

if not isfile("Dances/lux.ogg") then
	writefile("Dances/lux.ogg",
	game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/lux.ogg?raw=true"))
	warn("lux Downloaded! 28/"..tostring(HowMuch))
end

if not isfile("Dances/Mystery.mp3") then
	writefile("Dances/Mystery.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/Mystery.mp3?raw=true"))
	warn("Mystery Downloaded! 29/"..tostring(HowMuch))
end

if not isfile("Dances/Odetari - KEEP UP (Lyrics) (320kbps).mp3") then
	writefile("Dances/Odetari - KEEP UP (Lyrics) (320kbps).mp3",
	game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/Odetari%20-%20KEEP%20UP%20(Lyrics)%20(320kbps).mp3?raw=true"))
	warn("Odetari - KEEP UP (Lyrics) (320kbps) Downloaded! 30/"..tostring(HowMuch))
end

if not isfile("Dances/order.mp3") then
	writefile("Dances/order.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/order.mp3?raw=true"))
	warn("order Downloaded! 31/"..tostring(HowMuch))
end

if not isfile("Dances/pogo.mp3") then
	writefile("Dances/pogo.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/pogo.mp3?raw=true"))
	warn("pogo Downloaded! 32/"..tostring(HowMuch))
end

if not isfile("Dances/Pp music.mp3") then
	writefile("Dances/Pp music.mp3",
	game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/Pp%20music.mp3?raw=true"))
	warn("Pp music Downloaded! 33/"..tostring(HowMuch))
end

if not isfile("Dances/Shuba duck.mp3") then
	writefile("Dances/Shuba duck.mp3",
	game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/Shuba%20duck.mp3?raw=true"))
	warn("Shuba duck Downloaded! 34/"..tostring(HowMuch))
end

if not isfile("Dances/sturdy.mp3") then
	writefile("Dances/sturdy.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/sturdy.mp3?raw=true"))
	warn("sturdy Downloaded! 35/"..tostring(HowMuch))
end

if not isfile("Dances/true_heart.mp3") then
	writefile("Dances/true_heart.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/true_heart.mp3?raw=true"))
	warn("true_heart Downloaded! 36/"..tostring(HowMuch))
end

if not isfile("Dances/tryna.mp3") then
	writefile("Dances/tryna.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/tryna.mp3?raw=true"))
	warn("tryna Downloaded! 37/"..tostring(HowMuch))
end

if not isfile("Dances/TUNCA DONKA.mp3") then
	writefile("Dances/TUNCA DONKA.mp3",
	game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/TUNCA%20DONKA.mp3?raw=true"))
	warn("TUNCA DONKA Downloaded! 38/"..tostring(HowMuch))
end

if not isfile("Dances/valen.mp3") then
	writefile("Dances/valen.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/valen.mp3?raw=true"))
	warn("valen Downloaded! 39/"..tostring(HowMuch))
end

if not isfile("Dances/whateverlike.mp3") then
	writefile("Dances/whateverlike.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/whateverlike.mp3?raw=true"))
	warn("whateverlike Downloaded! 40/"..tostring(HowMuch))
end

if not isfile("Dances/XO.mp3") then
	writefile("Dances/XO.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/XO.mp3?raw=true"))
	warn("XO Downloaded! 41/"..tostring(HowMuch))
end

if not isfile("Dances/xxanteria, isq - FUNKED UP (SLOWED) (320kbps.mp3") then
	writefile("Dances/xxanteria, isq - FUNKED UP (SLOWED) (320kbps.mp3",
	game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/xxanteria%2C%20isq%20-%20FUNKED%20UP%20(SLOWED)%20(320kbps).mp3?raw=true"))
	warn("xxanteria, isq - FUNKED UP (SLOWED) (320kbps Downloaded! 42/"..tostring(HowMuch))
end

if not isfile("Dances/ТРИ ПОЛОСКИ ⧸ KOLM TRIIPU ⧸ THREE STRIPES.mp3") then
	writefile("Dances/ТРИ ПОЛОСКИ ⧸ KOLM TRIIPU ⧸ THREE STRIPES.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/%D0%A2%D0%A0%D0%98%20%D0%9F%D0%9E%D0%9B%D0%9E%D0%A1%D0%9A%D0%98%20%E2%A7%B8%20KOLM%20TRIIPU%20%E2%A7%B8%20THREE%20STRIPES.mp3?raw=true"))
	warn("ТРИ ПОЛОСКИ ⧸ KOLM TRIIPU ⧸ THREE STRIPES Downloaded! 43/"..tostring(HowMuch))
end

if not isfile("Dances/rat.mp3") then
	writefile("Dances/rat.mp3", game:HttpGet("https://github.com/Solary-3/Scripts/blob/Audios-1/rat.mp3?raw=true"))
	warn("rat Downloaded! 44/"..tostring(HowMuch))
end


game:GetService("StarterGui"):SetCore("SendNotification", {
	Title = "Notification",
	Text = "Songs Have been downloaded. Enjoy!",
	Duration = 3
})

game:GetService("StarterGui"):SetCore("SendNotification", {
	Title = "Notification",
	Text = "Songs Have been downloaded. Enjoy!",
	Duration = 3
})
